#!/usr/bin/env python3
"""
Find LinkedIn's data-export download-ready emails via Gmail, for the PKH
LinkedIn Export Connector desktop app.

Verified against a real account 2026-08-09 (searched Gmail directly): there
is NO separate "we received your request" confirmation email. LinkedIn
sends exactly two sequential download-ready emails per request instead:
  1. "The first installment of your LinkedIn data archive is ready!"
     (fast, arrives quickly)
  2. "Your full LinkedIn data archive is ready!" (~24h later; its own body
     says "we've finished putting together the second part")
Both link to the same URL shape (linkedin.com/comm/psettings/member-data),
told apart only by subject wording -- see PART1_KEYWORDS/PART2_KEYWORDS.
Both must be downloaded: Certifications/Skills/Learning are expected in the
"full" part based on LinkedIn's own fast/full internal naming, not the fast
one.

check_export_status(since_iso) scans LinkedIn mail received after a given
timestamp and returns every part found so far (not just the "best" one --
part1 needs downloading as soon as it's seen, independent of part2).

Uses a first-run *interactive* OAuth consent (opens a local browser, no
pre-existing token needed) -- a different trust model from gmail_sync.py's
non-interactive CI flow (pre-issued GMAIL_REFRESH_TOKEN env var, meant for
GitHub Actions secrets). Not sharing code with gmail_sync.py beyond
common.py's MIME helpers -- it's a working, independently-scheduled script
solving a different problem, not worth coupling to a new one.

CLI:
  python ingest/linkedin_export_email.py --check-once --since 2026-08-09T10:00:00Z
"""
import argparse
import email.utils
import json
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import get_header, get_message_text  # noqa: E402

ROOT = Path(__file__).parent.parent
# Both live with the app (connector/), not in data/ — data/ is PKH's own
# knowledge-corpus material. The client secret is the *app's* identity with
# Google, meant to ship bundled with the app and never touched by an end
# user; the token is this installation's granted access, generated by the
# one-time consent popup, not something anyone hand-edits either.
CLIENT_SECRET_FILE = ROOT / "connector" / "gmail_client_secret.json"
TOKEN_FILE = ROOT / "connector" / "gmail_token.json"

SCOPES = ["https://www.googleapis.com/auth/gmail.readonly"]

try:
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from googleapiclient.discovery import build
except ImportError:
    import subprocess
    subprocess.run(
        [sys.executable, "-m", "pip", "install",
         "google-api-python-client", "google-auth-httplib2", "google-auth-oauthlib",
         "-q", "--break-system-packages"],
        check=True,
    )
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from googleapiclient.discovery import build


# ---------------------------------------------------------------------------
# Auth — first-run interactive consent, cached token reused after that
# ---------------------------------------------------------------------------

def get_credentials(client_secret_path: Path = CLIENT_SECRET_FILE,
                     token_path: Path = TOKEN_FILE) -> Credentials:
    creds = None
    if token_path.exists():
        creds = Credentials.from_authorized_user_file(str(token_path), SCOPES)

    if creds and creds.valid:
        print("STATUS: using saved Gmail connection")
        return creds

    if creds and creds.expired and creds.refresh_token:
        print("STATUS: refreshing Gmail connection")
        creds.refresh(Request())
        token_path.write_text(creds.to_json(), encoding="utf-8")
        return creds

    if not client_secret_path.exists():
        raise FileNotFoundError(
            f"Gmail not connected yet, and no client secret file found at "
            f"{client_secret_path}. One-time setup: create a Desktop-app OAuth "
            f"client in Google Cloud Console and save its JSON there."
        )

    print("STATUS: opening browser for Gmail permission (read-only, one-time)")
    flow = InstalledAppFlow.from_client_secrets_file(str(client_secret_path), SCOPES)
    creds = flow.run_local_server(port=0)
    token_path.parent.mkdir(parents=True, exist_ok=True)
    token_path.write_text(creds.to_json(), encoding="utf-8")
    print("STATUS: Gmail connected")
    return creds


def build_gmail_service(creds: Credentials) -> object:
    return build("gmail", "v1", credentials=creds)


# ---------------------------------------------------------------------------
# Finding + classifying the right email(s)
# ---------------------------------------------------------------------------

LINKEDIN_QUERY = "(from:linkedin.com OR from:e.linkedin.com OR from:email.linkedin.com)"

# Confirmed against a real account 2026-08-09 (searched Gmail directly —
# see session notes): LinkedIn sends NO "we received your request"
# confirmation email at all. What it actually sends, for a single export
# request, is two sequential download-ready emails:
#   1. "The first installment of your LinkedIn data archive is ready!"
#      (arrives fast — LinkedIn's own tracking tag calls this "fast_part_01")
#   2. "Your full LinkedIn data archive is ready!" (arrives ~24h later,
#      tagged "full_part_01" — its body literally says "we've finished
#      putting together the second part of your data archive")
# Both parts must be downloaded — Certifications/Skills/Learning are
# expected in the "full" part based on the fast/full naming, not the fast
# one. Both emails link to the exact same URL shape
# (linkedin.com/comm/psettings/member-data?...), so parts are told apart by
# subject wording, not by the link itself.
PART1_KEYWORDS = ["first installment", "fast file"]
PART2_KEYWORDS = ["full linkedin data archive", "second part", "full archive"]

DOWNLOAD_LINK_PATTERNS = [
    r"https://www\.linkedin\.com/comm/psettings/member-data\?[^\s\"'<>]*",
    # Fallbacks in case LinkedIn changes the path — untested, kept defensive.
    r"https://www\.linkedin\.com/[^\s\"'<>]*download[^\s\"'<>]*",
    r"https://www\.linkedin\.com/[^\s\"'<>]*member-data[^\s\"'<>]*",
]


def extract_download_link(text: str) -> str | None:
    for pattern in DOWNLOAD_LINK_PATTERNS:
        m = re.search(pattern, text)
        if m:
            return m.group(0)
    return None


def classify_part(subject: str) -> str:
    s = subject.lower()
    if any(kw in s for kw in PART1_KEYWORDS):
        return "part1"
    if any(kw in s for kw in PART2_KEYWORDS):
        return "part2"
    return "unknown"


def _parse_message_date(headers: list[dict]) -> datetime | None:
    raw = get_header(headers, "date")
    if not raw:
        return None
    try:
        return email.utils.parsedate_to_datetime(raw)
    except Exception:
        return None


def find_linkedin_emails_since(service, since_dt: datetime, max_results: int = 10) -> list[dict]:
    query = f"{LINKEDIN_QUERY} after:{since_dt.strftime('%Y/%m/%d')}"
    results = service.users().messages().list(userId="me", q=query, maxResults=max_results).execute()
    refs = results.get("messages", [])

    messages = []
    for ref in refs:
        msg = service.users().messages().get(userId="me", id=ref["id"], format="full").execute()
        headers = msg["payload"].get("headers", [])
        msg_date = _parse_message_date(headers)
        # Gmail's `after:` filter is day-granularity only — re-filter to the
        # exact requested timestamp so an unrelated LinkedIn email earlier
        # the same day isn't mistaken for the confirmation/ready email.
        if msg_date and msg_date < since_dt:
            continue
        messages.append(msg)
    return messages


def classify_email(subject: str, body: str) -> dict | None:
    """Returns a part record if this email carries a download link, else
    None (not every LinkedIn email in the window is export-related — job
    alerts, connection notifications etc. also match the broad sender
    query)."""
    download_url = extract_download_link(body) or extract_download_link(subject)
    if not download_url:
        return None
    return {"part": classify_part(subject), "download_url": download_url}


def check_export_status(since_iso: str) -> dict:
    """Scan LinkedIn mail since `since_iso` (ISO timestamp) for ready-to-
    download parts. Returns every part found (there's no single "best"
    status here — part1 needs downloading as soon as it's seen, not just
    once part2 also arrives), plus a convenience `status` field for simple
    callers: "waiting" (nothing yet — normal, not an error), "partial"
    (only part1 found so far), or "complete" (both parts found)."""
    creds = get_credentials()
    service = build_gmail_service(creds)

    since_dt = datetime.fromisoformat(since_iso.replace("Z", "+00:00"))
    print(f"STATUS: checking Gmail for LinkedIn export emails since {since_iso}")
    messages = find_linkedin_emails_since(service, since_dt)
    print(f"STATUS: found {len(messages)} LinkedIn email(s) in that window")

    parts: dict[str, dict] = {}
    for msg in messages:
        headers = msg["payload"].get("headers", [])
        subject = get_header(headers, "subject")
        body = get_message_text(msg)
        record = classify_email(subject, body)
        if not record:
            continue
        msg_date = _parse_message_date(headers)
        record["email_subject"] = subject
        record["email_date"] = msg_date.isoformat() if msg_date else None
        # Keep the first match per part — re-running --check-once shouldn't
        # flip-flop which email "counts" if somehow more than one matches.
        parts.setdefault(record["part"], record)

    if "part2" in parts:
        status = "complete"
    elif "part1" in parts or "unknown" in parts:
        status = "partial"
    else:
        status = "waiting"

    return {"status": status, "parts": parts}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    p = argparse.ArgumentParser(
        description="Check Gmail for LinkedIn data-export download-ready emails (part 1 and part 2)."
    )
    p.add_argument("--check-once", action="store_true", help="Run a single check and exit")
    p.add_argument("--since", required=True,
                   help="ISO timestamp (e.g. 2026-08-09T10:00:00Z) the export was requested at")
    args = p.parse_args()

    if not args.check_once:
        print("Only --check-once is supported currently.")
        sys.exit(1)

    try:
        result = check_export_status(args.since)
    except Exception as e:
        print(f"ERROR: {e}")
        print("PKH_JSON_SUMMARY: " + json.dumps({"ok": False, "error": str(e)}))
        sys.exit(1)

    print(f"STATUS: result = {result['status']}")
    print("PKH_JSON_SUMMARY: " + json.dumps({"ok": True, **result}))
